# Generated by Django 5.2.8 on 2025-12-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cardapio_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='tipo',
        ),
    ]
