# Generated by Django 5.2.8 on 2025-12-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cardapio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tipo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
